#!/usr/bin/env bash
reset

valgrind \
    --exit-on-first-error=yes \
    --leak-check=full \
    --show-leak-kinds=all \
    --track-origins=yes \
    --suppressions=./scripts/valgrind.supp ./bin/"$1" "${@:2}"