#!/bin/bash

# clone utf8proc
if ! find /usr/local/lib /usr/lib /lib -type f -name 'libutf8proc*' -print -quit | grep -q .; then
    wget https://github.com/JuliaStrings/utf8proc/releases/download/v2.10.0/utf8proc-2.10.0.tar.gz
    tar -xf ./utf8proc-2.10.0.tar.gz
    rm -f ./utf8proc-2.10.0.tar.gz

    # build utf8proc
    cd ./utf8proc*
    make
    make install

    # building server
    cd ..
fi

./code/scripts/rbuild router "$1"

cd ./code/py
python -m venv venv
source ./venv/bin/activate
pip install -r ./requirements.txt
deactivate
cd -

mkdir -p bin
mkdir -p assets/databases
echo "Done"