#!/usr/bin/env bash

reset
gcc-14 -fsanitize=address -fno-omit-frame-pointer -pedantic -Wall -Wextra -g -O2 -o  "$1" ./"$1".c ./csrs/* -I src -lm -lutf8proc  \
&& printf "\n\n" \
&& ./"$1"

mv ./"$1" ./bin